# server/dockerfile
FROM node:23-alpine
RUN apk add --no-cache curl
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm config set strict-ssl false
RUN npm install --verbose
COPY . .
RUN npm run build
EXPOSE 3000
CMD ["npm", "run", "serve"]