# web/dockerfile
FROM node:22-alpine
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm config set strict-ssl false
RUN npm install --verbose
COPY . .
RUN npm run build
EXPOSE 80 443
CMD ["npm", "run", "start"]